#!/usr/bin/python3
from os import listdir, system
from colorama import init as colorama_init
from colorama import Fore
import subprocess

def parse_diff_output(output: str) -> str:
    try:
        if output == "":
            return output
        lines: list[str] = output.splitlines()
        i = lines.index("---")
        return f"Expected:\n\t{"\n".join(list(map(lambda l: l.lstrip('< '), lines[1 + 2:])))}\nGot:\n\t{"\n".join(list(map(lambda l: l.lstrip('> '), lines[1:i])))}"
    except ValueError:
        return output

def run_test(binary: str, name: str) -> bool:
    if subprocess.run(
        [binary, f"test/compile_tests/{name}"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    ).returncode == 0:
        print(f"{Fore.GREEN}TEST {name} PASSED!")
        return True
    print(f"\033[1m{Fore.RED}TEST {name} FAILED!\033[0m")
    return False

def get_binary_path() -> str:
    result = subprocess.run(
        ["stack", "path", "--local-install-root"],
        capture_output=True,
        text=True,
    )
    install_root = result.stdout.strip()
    return f"{install_root}/bin/mvscc"

def run_tests():
    system("stack build > /dev/null")
    binary = get_binary_path()
    files = listdir("./test/compile_tests")
    count: int = 0
    for file in files:
        if run_test(binary, file):
            count += 1
    if count != len(files):
        print(f"{count}/{len(files)} TESTS PASSED!")
        exit(1)
    print(f"{count}/{len(files)} TESTS PASSED!")
    exit(0)

def main():
    run_tests()

if __name__ == "__main__":
    main()
