name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell-actions/setup@v2.7.10

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Cache Cabal store
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          ~/.cabal/packages
          dist-newstyle
        key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-
          ${{ runner.os }}-ghc-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: python run_tests.py
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          dist-newstyle
        key: ${{ runner.os }}-build-artifacts-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-artifacts-
